### ISSUE TITLE
Look at consolidating the Async methods

### ISSUE THREAD

**Issue by ahazelwood** [DamianEdwards/RazorPagesSample#1]
I was looking at the Login page, and noticed that there is a OnPostAsync method and a OnGet method.  Should OnGet be renamed to:  OnGetAsync?   If not, why?

Thanks.  Keep up the good work.

See:  https://github.com/DamianEdwards/RazorPagesSample/blob/master/RazorPagesWebApplication/Pages/Account/Login.cshtml.cs

**Comment by DamianEdwards** [comment]
Yeah, just typos, thanks. I'll clean it up. The framework supports dispatching to both, so the `Async` suffix is optional.
