### ISSUE TITLE
Similarities with UWP

### ISSUE THREAD

**Issue by Ponant** [DamianEdwards/RazorPagesSample#13]
Hi @DamianEdwards , 
Just to get a picture, are razorPages somewhat the equivalent of UWP with a front page and a code behind? Is this the philosophy behind them? :)

**Comment by mikebrind** [comment]
@Ponant Yes, Razor Pages is an implementation of the Page Controller pattern in that each page has (can have) a controller in the form of a code-behind file. This is similar to the ASP.NET Web Forms framework and XAML-based projects.

**Comment by Ponant** [comment]
@mikebrind , thanks Mike for confirming. Do you think we can do big apps (heavy loads etc)? I would say so.

**Comment by mikebrind** [comment]
Sure. It's built on .NET Core MVC. It includes separation of concerns and testability as first class features.

**Comment by Ponant** [comment]
OK great, thank you again for your time @mikebrind !
